# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: NPM Publisher
      # You may pin to the exact commit or the version.
      # uses: lyzhang1999/npm-publish@61d419d5bb515116b1745c3da8575d37c58edff7
      - uses: lyzhang1999/npm-publish@v1.0.2
          
